import { CloudService } from './tcb';
import { MediaResource } from '../types';

export type FeedbackType = 'bug' | 'feature' | 'other' | 'report_user';
export type FeedbackStatus = 'pending' | 'processing' | 'resolved' | 'rejected';
export type ReportReason =
  | 'spam'
  | 'abuse'
  | 'harassment'
  | 'pornography'
  | 'violence'
  | 'fraud'
  | 'other';

export interface FeedbackData {
  _id?: string;
  userId: string;
  type: FeedbackType;
  content: string;
  contact?: string;
  status?: FeedbackStatus;
  createdAt?: string;
  media?: MediaResource[];
  targetUserId?: string;
  targetDiaryId?: string;
  reportReason?: ReportReason;
  targetSnapshot?: {
    _id?: string;
    nickname?: string;
    avatar?: string;
    phone?: string;
  };
  targetDiarySnapshot?: {
    _id?: string;
    title?: string;
    content?: string;
    mediaCount?: number;
  };
  reporterSnapshot?: {
    _id?: string;
    nickname?: string;
    avatar?: string;
    phone?: string;
  };
  blockerSnapshot?: {
    _id?: string;
    nickname?: string;
    avatar?: string;
    phone?: string;
  };
  source?: string;
  governanceTrigger?: string;
  autoGenerated?: boolean;
  reviewedBy?: string;
  reviewedAt?: string;
  reviewNote?: string;
  blockRelationCreatedAt?: number;
}

export interface FeedbackListResponse {
  list: FeedbackData[];
  total: number;
  page: number;
  pageSize: number;
}

export interface AdminFeedbackListParams {
  adminUserId: string;
  page?: number;
  pageSize?: number;
  status?: FeedbackStatus | 'all';
}

export interface AdminUserFeedbackListParams {
  adminUserId: string;
  page?: number;
  pageSize?: number;
  type?: FeedbackType | 'all';
}

export interface AdminFeedbackDetailParams {
  adminUserId: string;
  feedbackId: string;
}

export class FeedbackService {
  /**
   * 提交反馈
   */
  async submitFeedback(
    data: Omit<FeedbackData, '_id' | 'status' | 'createdAt'>
  ): Promise<FeedbackData> {
    try {
      const response: any = await CloudService.callFunction('feedback', {
        action: 'add',
        data,
      });

      if (response.code === 0 && response.data) {
        const cloudResult = response.data;
        if (cloudResult.success && cloudResult.data) {
          return cloudResult.data;
        }
      }

      throw new Error(response.message || '提交反馈失败');
    } catch (error) {
      console.error('FeedbackService.submitFeedback error:', error);
      throw error;
    }
  }

  async submitUserReport(data: {
    userId: string;
    targetUserId: string;
    targetDiaryId?: string;
    reportReason: ReportReason;
    content: string;
    contact?: string;
    media?: MediaResource[];
    targetSnapshot?: {
      nickname?: string;
      avatar?: string;
    };
    targetDiarySnapshot?: {
      _id?: string;
      title?: string;
      content?: string;
      mediaCount?: number;
    };
  }): Promise<FeedbackData> {
    return this.submitFeedback({
      ...data,
      type: 'report_user',
    });
  }

  /**
   * 获取用户的反馈列表
   */
  async getMyFeedbacks(userId: string, page = 1, pageSize = 20): Promise<FeedbackListResponse> {
    try {
      const response: any = await CloudService.callFunction('feedback', {
        action: 'list',
        data: {
          userId,
          page,
          pageSize,
        },
      });

      if (response.code === 0 && response.data) {
        const cloudResult = response.data;
        if (cloudResult.success && cloudResult.data) {
          return cloudResult.data;
        }
      }

      throw new Error(response.message || '获取反馈列表失败');
    } catch (error) {
      console.error('FeedbackService.getMyFeedbacks error:', error);
      throw error;
    }
  }

  async getAdminReviewList(params: AdminFeedbackListParams): Promise<FeedbackListResponse> {
    try {
      const response: any = await CloudService.callFunction('feedback', {
        action: 'adminList',
        data: {
          page: 1,
          pageSize: 20,
          status: 'pending',
          ...params,
        },
      });

      if (response.code === 0 && response.data) {
        const cloudResult = response.data;
        if (cloudResult.success && cloudResult.data) {
          return cloudResult.data;
        }
      }

      throw new Error(response.data?.message || response.message || '获取审核列表失败');
    } catch (error) {
      console.error('FeedbackService.getAdminReviewList error:', error);
      throw error;
    }
  }

  async getAdminUserFeedbackList(params: AdminUserFeedbackListParams): Promise<FeedbackListResponse> {
    try {
      const response: any = await CloudService.callFunction('feedback', {
        action: 'adminUserFeedbackList',
        data: {
          page: 1,
          pageSize: 20,
          type: 'all',
          ...params,
        },
      });

      if (response.code === 0 && response.data) {
        const cloudResult = response.data;
        if (cloudResult.success && cloudResult.data) {
          return cloudResult.data;
        }
      }

      throw new Error(response.data?.message || response.message || '获取用户反馈列表失败');
    } catch (error) {
      console.error('FeedbackService.getAdminUserFeedbackList error:', error);
      throw error;
    }
  }

  async getAdminPendingCount(adminUserId: string): Promise<number> {
    try {
      const response: any = await CloudService.callFunction('feedback', {
        action: 'adminPendingCount',
        data: {
          adminUserId,
        },
      });

      if (response.code === 0 && response.data?.success) {
        return response.data.data || 0;
      }

      throw new Error(response.data?.message || response.message || '获取待处理数量失败');
    } catch (error) {
      console.error('FeedbackService.getAdminPendingCount error:', error);
      throw error;
    }
  }

  async getAdminReviewDetail(params: AdminFeedbackDetailParams): Promise<FeedbackData> {
    try {
      const response: any = await CloudService.callFunction('feedback', {
        action: 'adminDetail',
        data: params,
      });

      if (response.code === 0 && response.data?.success && response.data.data) {
        return response.data.data;
      }

      throw new Error(response.data?.message || response.message || '获取审核记录详情失败');
    } catch (error) {
      console.error('FeedbackService.getAdminReviewDetail error:', error);
      throw error;
    }
  }

  async updateAdminReviewStatus(data: {
    adminUserId: string;
    feedbackId: string;
    status: FeedbackStatus;
    reviewNote?: string;
  }): Promise<boolean> {
    try {
      const response: any = await CloudService.callFunction('feedback', {
        action: 'adminUpdate',
        data,
      });

      if (response.code === 0 && response.data?.success) {
        return true;
      }

      throw new Error(response.data?.message || response.message || '更新审核状态失败');
    } catch (error) {
      console.error('FeedbackService.updateAdminReviewStatus error:', error);
      throw error;
    }
  }

  /**
   * 删除反馈
   */
  async deleteFeedback(feedbackId: string, userId: string): Promise<boolean> {
    try {
      const response: any = await CloudService.callFunction('feedback', {
        action: 'delete',
        data: {
          _id: feedbackId,
          userId,
        },
      });

      if (response.code === 0 && response.data) {
        const cloudResult = response.data;
        if (cloudResult.success) {
          return true;
        }
      }

      throw new Error(response.message || '删除反馈失败');
    } catch (error) {
      console.error('FeedbackService.deleteFeedback error:', error);
      throw error;
    }
  }
}

export default new FeedbackService();
